# Rotina a ser executada após efetuar o commit na branch develope. Ela irá fazer o deploy da aplicação no ambiente de teste. 
name: Develop-builder
on:
  workflow_dispatch:
  push:
    branches: [ develop ]
    
jobs:
  builder:
    name: builder java file
    runs-on: self-hosted
    steps:
      - name: Limpar diretório existente e clonar repositório no branch develop
        run: |
           ls
           echo "Limpar diretório existente e clonar repositório no branch develop"
#          cd ..
#          rm -rf *
#          git clone --branch develop https://github.com/EmersonMorgado/afinese.git
          
      - name: Builder da aplicação
        run: |
           ls
           echo "Builder da aplicação"
#          mvn clean
#          mvn install
  copy:
    needs: [builder]
    name: Parar a aplicação atual e subir a nova
    runs-on: self-hosted
    steps:
      - name: Parar a aplicação atual
        run: |
           ls
           echo "Parar a aplicação atual"
# 
      - name: Copiar a nova aplicação
        run: |
           ls
           echo "Copiar a nova aplicação"
#        
  deploy-develop:
    needs: [copy]
    name: deploy application
    runs-on: self-hosted
    steps:
      - name: Deploy da aplicação no ambiente de homologação
        run: |
          ls $HOME
